### ISSUE TITLE
feat: implement image block

### ISSUE THREAD

**Issue by invisal** [invisal/khmercoders#18]
When blog contains the image, it will use show JSON data instead of actually render the image. Please add the image rendering support.

**Comment by rin-yato** [comment]
For anyone planning to pick this up:

You may refer to this docs for the recommended Image component by nextjs

https://nextjs.org/docs/pages/api-reference/components/image

Make sure to check the next.config.mjs, since normally the Image component doesnt allow fetching remote images, unless you specify the allowed origin

https://nextjs.org/docs/pages/api-reference/components/image#configuration-options

**Comment by soknaly** [comment]
@invisal @rin-yato I'll take this

**Comment by soknaly** [comment]
Anyone can pick this if you have time for now. I will be occupied until tonight.
